# Generated by Django 4.1.1 on 2022-09-28 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa projektu')),
                ('client_company', models.CharField(max_length=50, verbose_name='Nazwa firmy')),
                ('location', models.CharField(max_length=50, verbose_name='Lokalizacja firmy')),
                ('finished', models.BooleanField(default=False, verbose_name='Projekt ukończony')),
            ],
            options={
                'verbose_name': 'Projekt',
                'verbose_name_plural': 'Projekty',
            },
        ),
        migrations.CreateModel(
            name='WorkhoursRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(auto_now_add=True, verbose_name='Start pracy')),
                ('stop', models.DateTimeField(verbose_name='Koniec pracy')),
                ('status', models.CharField(choices=[('P', 'Praca'), ('U', 'Urlop'), ('C', 'Choroba'), ('O', 'Opieka')], default='P', max_length=20, verbose_name='Status')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Pracownik')),
            ],
            options={
                'verbose_name': 'Dzień Pracy',
                'verbose_name_plural': 'Dni Pracy',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(auto_now_add=True, verbose_name='Początek zadania')),
                ('stop', models.DateTimeField(verbose_name='Zakończenie zadania')),
                ('location', models.CharField(max_length=50, verbose_name='Miejsce pracy')),
                ('work_mode', models.CharField(choices=[('HO', 'Home office'), ('F', 'W Firmie'), ('D', 'Delegacja'), ('S', 'Serwis')], max_length=20, verbose_name='Tryb pracy')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.projects', verbose_name='Projekt')),
                ('work_day', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.workhoursregistry', verbose_name='Dzień pracy')),
            ],
            options={
                'verbose_name': 'Zadanie',
                'verbose_name_plural': 'Zadania',
            },
        ),
    ]
