# Generated by Django 4.1.1 on 2022-09-29 13:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_task_start_alter_workhoursregistry_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Początek zadania'),
        ),
        migrations.AlterField(
            model_name='workhoursregistry',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start pracy'),
        ),
    ]
