# Generated by Django 4.1.1 on 2022-10-03 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_task_start_alter_workhoursregistry_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workhoursregistry',
            name='stop',
            field=models.DateTimeField(null=True, verbose_name='Koniec pracy'),
        ),
    ]
