# Generated by Django 4.1.1 on 2022-10-06 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_alter_task_stop'),
    ]

    operations = [
        migrations.CreateModel(
            name='OvertimeParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overtime_after', models.IntegerField(verbose_name='Nadgodziny po')),
                ('overtime_days', models.IntegerField(verbose_name='Dzien nadgodzin')),
            ],
            options={
                'verbose_name': 'Parametr Nadgodzin',
                'verbose_name_plural': 'Parametry Nadgodzin',
            },
        ),
    ]
