# Generated by Django 4.1.1 on 2022-09-28 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserCustom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='Email')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='Ostatnie logowanie')),
                ('first_name', models.CharField(max_length=30, verbose_name='Imie')),
                ('last_name', models.CharField(max_length=50, verbose_name='Nazwisko')),
                ('mobile_nr', models.CharField(max_length=15, verbose_name='Nr telefonu')),
                ('pesel', models.CharField(max_length=11, verbose_name='Nr PESEL')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Administrator')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Pracownik')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Glowny administrator')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywny')),
                ('holiday_allowance', models.IntegerField(default=0, verbose_name='Wymiar urlopu')),
            ],
            options={
                'verbose_name': 'Pracownik',
                'verbose_name_plural': 'Pracownicy',
            },
        ),
    ]
